//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 02:09:18 PM GMT 
//


package is.hi.vinnsla;
import is.hi.vinnsla.ObjectFactory;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "root", propOrder = {
    "vedurstod"})
@XmlRootElement(name = "root")

public class Nidurstodur {

        @XmlElement(name="results")   
        protected List<Nidurstodur.Vedurstod> vedurstod;

        /**
         * Gets the value of the vedurstod property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vedurstod property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVedurstod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Nidurstodur.AllarStodvar.Vedurstod }
         * 
         * 
         */
        public List<Nidurstodur.Vedurstod> getVedurstod() {
            if (vedurstod == null) {
                vedurstod = new ArrayList<Nidurstodur.Vedurstod>();
            }
            return this.vedurstod;
        }


        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "atime",
            "err",
            "vedurspa",
            "id",
            "link",
            "name",
            "valid"
        })
        public static class Vedurstod {

            @XmlElement(required = true)
            protected String atime;
            @XmlElement(required = true)
            protected String err;
            @XmlElement(name="forecast", required = true)
            protected List<Nidurstodur.Vedurstod.Vedurspa> vedurspa;
            protected short id;
            @XmlElement(required = true)
            @XmlSchemaType(name = "anyURI")
            protected String link;
            @XmlElement(required = true)
            protected String name;
            protected byte valid;

            /**
             * Viðótar aðferð til að ná í lýsingu á veðurstöð
             * @return 
             */
            @Override 
            public String toString() {
                return name;
            }
            /**
             * Gets the value of the atime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAtime() {
                return atime;
            }

            /**
             * Sets the value of the atime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAtime(String value) {
                this.atime = value;
            }

            /**
             * Gets the value of the err property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getErr() {
                return err;
            }

            /**
             * Sets the value of the err property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setErr(String value) {
                this.err = value;
            }

            /**
             * Gets the value of the spaStodvar property.
             * 
             * @return
             *     possible object is
             *     {@link Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar }
             *     
             */
           public List<Nidurstodur.Vedurstod.Vedurspa> getVedurspa() {
                    if (vedurspa == null) {
                        vedurspa = new ArrayList<Nidurstodur.Vedurstod.Vedurspa>();
                    }
                    return this.vedurspa;
                }

            /**
             * Sets the value of the spaStodvar property.
             * 
             * @param value
             *     allowed object is
             *     {@link Nidurstodur.AllarStodvar.Vedurstod.SpaStodvar }
             *     
             */
            public void setVedurspa(List<Nidurstodur.Vedurstod.Vedurspa> value) {
                this.vedurspa = value;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public short getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(short value) {
                this.id = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink(String value) {
                this.link = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the valid property.
             * 
             */
            public byte getValid() {
                return valid;
            }

            /**
             * Sets the value of the valid property.
             * 
             */
            public void setValid(byte value) {
                this.valid = value;
            }

           
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "d",
                    "f",
                    "n",
                    "r",
                    "t",
                    "td",
                    "w",
                    "ftime"
                })

                public static class Vedurspa {

                    @XmlElement(name = "D", required = true)
                    protected String d;
                    @XmlElement(name = "F")
                    protected byte f;
                    @XmlElement(name = "N")
                    protected byte n;
                    @XmlElement(name = "R")
                    protected float r;
                    @XmlElement(name = "T")
                    protected byte t;
                    @XmlElement(name = "TD")
                    protected byte td;
                    @XmlElement(name = "W", required = true)
                    protected String w;
                    @XmlElement(required = true)
                    protected String ftime;

                    /**
                     * Gets the value of the d property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getD() {
                        return d;
                    }

                    /**
                     * Sets the value of the d property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setD(String value) {
                        this.d = value;
                    }

                    /**
                     * Gets the value of the f property.
                     * 
                     */
                    public byte getF() {
                        return f;
                    }

                    /**
                     * Sets the value of the f property.
                     * 
                     */
                    public void setF(byte value) {
                        this.f = value;
                    }

                    /**
                     * Gets the value of the n property.
                     * 
                     */
                    public byte getN() {
                        return n;
                    }

                    /**
                     * Sets the value of the n property.
                     * 
                     */
                    public void setN(byte value) {
                        this.n = value;
                    }

                    /**
                     * Gets the value of the r property.
                     * 
                     */
                    public float getR() {
                        return r;
                    }

                    /**
                     * Sets the value of the r property.
                     * 
                     */
                    public void setR(float value) {
                        this.r = value;
                    }

                    /**
                     * Gets the value of the t property.
                     * 
                     */
                    public byte getT() {
                        return t;
                    }

                    /**
                     * Sets the value of the t property.
                     * 
                     */
                    public void setT(byte value) {
                        this.t = value;
                    }

                    /**
                     * Gets the value of the td property.
                     * 
                     */
                    public byte getTD() {
                        return td;
                    }

                    /**
                     * Sets the value of the td property.
                     * 
                     */
                    public void setTD(byte value) {
                        this.td = value;
                    }

                    /**
                     * Gets the value of the w property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getW() {
                        return w;
                    }

                    /**
                     * Sets the value of the w property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setW(String value) {
                        this.w = value;
                    }

                    /**
                     * Gets the value of the ftime property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFtime() {
                        return ftime;
                    }

                    /**
                     * Sets the value of the ftime property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFtime(String value) {
                        this.ftime = value;
                    }

                }

            }

        }

